https://www.kaggle.com/datasets/jessicali9530/celeba-dataset

In [1]:
import pandas as pd
from datasets import Dataset

## Dataset with vector

In [14]:
df = pd.read_csv('list_attr_celeba.csv')
df.head()

,image_id,5_o_Clock_Shadow,Arched_Eyebrows,Attractive,Bags_Under_Eyes,Bald,Bangs,Big_Lips,Big_Nose,Black_Hair,...,Sideburns,Smiling,Straight_Hair,Wavy_Hair,Wearing_Earrings,Wearing_Hat,Wearing_Lipstick,Wearing_Necklace,Wearing_Necktie,Young
0,000001.jpg,-1,1,1,-1,-1,-1,-1,-1,-1,...,-1,1,1,-1,1,-1,1,-1,-1,1
1,000002.jpg,-1,-1,-1,1,-1,-1,-1,1,-1,...,-1,1,-1,-1,-1,-1,-1,-1,-1,1
2,000003.jpg,-1,-1,-1,-1,-1,-1,1,-1,-1,...,-1,-1,-1,1,-1,-1,-1,-1,-1,1
3,000004.jpg,-1,-1,1,-1,-1,-1,-1,-1,-1,...,-1,-1,1,-1,1,-1,1,1,-1,1
4,000005.jpg,-1,1,1,-1,-1,-1,1,-1,-1,...,-1,-1,-1,-1,-1,-1,1,-1,-1,1

In [15]:
df.shape

(202599, 41)

In [3]:
df = df.drop(columns='5_o_Clock_Shadow')
df.head()

,image_id,Arched_Eyebrows,Attractive,Bags_Under_Eyes,Bald,Bangs,Big_Lips,Big_Nose,Black_Hair,Blond_Hair,...,Sideburns,Smiling,Straight_Hair,Wavy_Hair,Wearing_Earrings,Wearing_Hat,Wearing_Lipstick,Wearing_Necklace,Wearing_Necktie,Young
0,000001.jpg,1,1,-1,-1,-1,-1,-1,-1,-1,...,-1,1,1,-1,1,-1,1,-1,-1,1
1,000002.jpg,-1,-1,1,-1,-1,-1,1,-1,-1,...,-1,1,-1,-1,-1,-1,-1,-1,-1,1
2,000003.jpg,-1,-1,-1,-1,-1,1,-1,-1,-1,...,-1,-1,-1,1,-1,-1,-1,-1,-1,1
3,000004.jpg,-1,1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,1,-1,1,-1,1,1,-1,1
4,000005.jpg,1,1,-1,-1,-1,1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,1,-1,-1,1

In [4]:
vectors = df.iloc[:, 1:].to_numpy()
img_path = df.iloc[:, 0].to_list()

In [5]:
dataset = Dataset.from_dict({"images": img_path, "vectors": vectors})

In [6]:
dataset.save_to_disk("celeba_vectors")

Saving the dataset (0/1 shards):   0%|          | 0/202599 [00:00<?, ? examples/s]

## Dataset with prompt

In [7]:
df = pd.read_csv('list_attr_celeba.csv')
df.head()

,image_id,5_o_Clock_Shadow,Arched_Eyebrows,Attractive,Bags_Under_Eyes,Bald,Bangs,Big_Lips,Big_Nose,Black_Hair,...,Sideburns,Smiling,Straight_Hair,Wavy_Hair,Wearing_Earrings,Wearing_Hat,Wearing_Lipstick,Wearing_Necklace,Wearing_Necktie,Young
0,000001.jpg,-1,1,1,-1,-1,-1,-1,-1,-1,...,-1,1,1,-1,1,-1,1,-1,-1,1
1,000002.jpg,-1,-1,-1,1,-1,-1,-1,1,-1,...,-1,1,-1,-1,-1,-1,-1,-1,-1,1
2,000003.jpg,-1,-1,-1,-1,-1,-1,1,-1,-1,...,-1,-1,-1,1,-1,-1,-1,-1,-1,1
3,000004.jpg,-1,-1,1,-1,-1,-1,-1,-1,-1,...,-1,-1,1,-1,1,-1,1,1,-1,1
4,000005.jpg,-1,1,1,-1,-1,-1,1,-1,-1,...,-1,-1,-1,-1,-1,-1,1,-1,-1,1

In [8]:
old_keys = ['Arched_Eyebrows', 'Attractive',
       'Bags_Under_Eyes', 'Bald', 'Bangs', 'Big_Lips', 'Big_Nose',
       'Black_Hair', 'Blond_Hair', 'Blurry', 'Brown_Hair', 'Bushy_Eyebrows',
       'Chubby', 'Double_Chin', 'Eyeglasses', 'Goatee', 'Gray_Hair',
       'Heavy_Makeup', 'High_Cheekbones', 'Male', 'Mouth_Slightly_Open',
       'Mustache', 'Narrow_Eyes', 'No_Beard', 'Oval_Face', 'Pale_Skin',
       'Pointy_Nose', 'Receding_Hairline', 'Rosy_Cheeks', 'Sideburns',
       'Smiling', 'Straight_Hair', 'Wavy_Hair', 'Wearing_Earrings',
       'Wearing_Hat', 'Wearing_Lipstick', 'Wearing_Necklace',
       'Wearing_Necktie', 'Young']

In [9]:
pos_new_keys = ["Изогнутые брови", "Привлекательность",
       "Мешки под глазами", "Лысый", "Челка", "Большие губы", "Большой нос",
       "Черные волосы", "Светлые волосы", "Размытые", "Коричневые волосы", "Густые брови",
       "Пухлость", "Двойной подбородок", "Очки", "Эспаньолка", "Седые волосы",
       "Сильный макияж", "Высокие скулы", "Мужчина", "Рот слегка открыт",
       "Усы", "Узкие глаза", "Без бороды", "Овальное лицо", "Бледная кожа",
       "Острый нос", "Залысины", "Розовые щеки", "Бакенбарды",
       "Улыбчивость", "Прямые волосы", "Волнистые волосы", "В серьгах",
       "В шляпе", "Губная помада", "Ожерелье",
       "В галстуке", "Молодость"]

neg_new_keys = ["Прямые брови", None,
       None, None, None, "Узкие губы", "Маленький нос",
       None, None, "Четкость", None, "Редкие брови",
       "Стройность", None, None, None, None,
       "Без макияжа", None, "Женщина", None,
       None, "Широкие глаза", None, None, "Загар",
       None, None, None, None,
       "Грусть", None, None, None,
       None, None, None,
       None, "Старость"]

In [10]:
desc = {old_key: {1: pos_key, -1: neg_key} for old_key, pos_key, neg_key in zip(old_keys, pos_new_keys, neg_new_keys)}

desc

{'Arched_Eyebrows': {1: 'Изогнутые брови', -1: 'Прямые брови'},
 'Attractive': {1: 'Привлекательность', -1: None},
 'Bags_Under_Eyes': {1: 'Мешки под глазами', -1: None},
 'Bald': {1: 'Лысый', -1: None},
 'Bangs': {1: 'Челка', -1: None},
 'Big_Lips': {1: 'Большие губы', -1: 'Узкие губы'},
 'Big_Nose': {1: 'Большой нос', -1: 'Маленький нос'},
 'Black_Hair': {1: 'Черные волосы', -1: None},
 'Blond_Hair': {1: 'Светлые волосы', -1: None},
 'Blurry': {1: 'Размытые', -1: 'Четкость'},
 'Brown_Hair': {1: 'Коричневые волосы', -1: None},
 'Bushy_Eyebrows': {1: 'Густые брови', -1: 'Редкие брови'},
 'Chubby': {1: 'Пухлость', -1: 'Стройность'},
 'Double_Chin': {1: 'Двойной подбородок', -1: None},
 'Eyeglasses': {1: 'Очки', -1: None},
 'Goatee': {1: 'Эспаньолка', -1: None},
 'Gray_Hair': {1: 'Седые волосы', -1: None},
 'Heavy_Makeup': {1: 'Сильный макияж', -1: 'Без макияжа'},
 'High_Cheekbones': {1: 'Высокие скулы', -1: None},
 'Male': {1: 'Мужчина', -1: 'Женщина'},
 'Mouth_Slightly_Open': {1: 'Рот слегка открыт', -1: None},
 'Mustache': {1: 'Усы', -1: None},
 'Narrow_Eyes': {1: 'Узкие глаза', -1: 'Широкие глаза'},
 'No_Beard': {1: 'Без бороды', -1: None},
 'Oval_Face': {1: 'Овальное лицо', -1: None},
 'Pale_Skin': {1: 'Бледная кожа', -1: 'Загар'},
 'Pointy_Nose': {1: 'Острый нос', -1: None},
 'Receding_Hairline': {1: 'Залысины', -1: None},
 'Rosy_Cheeks': {1: 'Розовые щеки', -1: None},
 'Sideburns': {1: 'Бакенбарды', -1: None},
 'Smiling': {1: 'Улыбчивость', -1: 'Грусть'},
 'Straight_Hair': {1: 'Прямые волосы', -1: None},
 'Wavy_Hair': {1: 'Волнистые волосы', -1: None},
 'Wearing_Earrings': {1: 'В серьгах', -1: None},
 'Wearing_Hat': {1: 'В шляпе', -1: None},
 'Wearing_Lipstick': {1: 'Губная помада', -1: None},
 'Wearing_Necklace': {1: 'Ожерелье', -1: None},
 'Wearing_Necktie': {1: 'В галстуке', -1: None},
 'Young': {1: 'Молодость', -1: 'Старость'}}

In [11]:
new_desc = {
       "image_id": [],
       "prompt": []
}
for _, row in df.iterrows():
       new_desc["image_id"].append(row['image_id'])
       prompt_list = []
       for key, prompt_keys in desc.items():
              res = prompt_keys[row[key]]
              if res is not None:
                     prompt_list.append(res)
       new_desc["prompt"].append(prompt_list)

In [12]:
new_df = pd.DataFrame(new_desc, dtype="object")
new_df.head()

     image_id                                             prompt
0  000001.jpg  [Изогнутые брови, Привлекательность, Узкие губ...
1  000002.jpg  [Прямые брови, Мешки под глазами, Узкие губы, ...
2  000003.jpg  [Прямые брови, Большие губы, Маленький нос, Ра...
3  000004.jpg  [Прямые брови, Привлекательность, Узкие губы, ...
4  000005.jpg  [Изогнутые брови, Привлекательность, Большие г...

In [13]:
dataset = Dataset.from_pandas(new_df)
dataset.save_to_disk("celeba_prompts")

Saving the dataset (0/1 shards):   0%|          | 0/202599 [00:00<?, ? examples/s]